---
- name: initial Orca API call
  uri:
    url: https://api.orcasecurity.io/api/threatoptix/download?agent_type=vm
    method: GET
    headers:
      Content-Type: "application/json"
      Authorization: "Token aHR0cHM6Ly9hcHAudXMub3JjYXNlY3VyaXR5LmlvfHx0dW56NUd4a2ZKSEl6TjB4RGJtU2xUeTJuM2t4M0FCSw=="
    return_content: true
    status_code: 200
    body_format: json
  register: result_from_threatoptix_download_api_call

- name: create opt/ThreatOptix directory
  shell: sudo mkdir -p /opt/ThreatOptix && sudo chmod 777 '/opt/ThreatOptix'

- name: Download TO Agent to /opt/ThreatOptix
  uri:
    url: '{{result_from_threatoptix_download_api_call.json["s3_signed_url"]}}'
    user: ec2-user
    method: GET
    dest: /opt/ThreatOptix
  register: result

- name: Change directory and unzip TO Agent tarball
  shell:  cd /opt/ThreatOptix && unzip ThreatOptix_agent_vm_v1.0.8.zip -d /opt/ThreatOptix

- name: Chmod of install script, uninstall script, to-monitor binary to allow execution
  shell: sudo chmod +x install.sh uninstall.sh bin/threatoptix-monitor
  
- name: Run install script
  shell: "sudo ./install.sh"